"""empty message

Revision ID: 1392585412d
Revises: 52979aa7977
Create Date: 2015-09-02 10:13:07.149291

"""

# revision identifiers, used by Alembic.
revision = '1392585412d'
down_revision = '52979aa7977'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    ### end Alembic commands ###
