"""empty message

Revision ID: 16b50a2c53b
Revises: 4a7e5abdf57
Create Date: 2015-12-21 14:51:48.537902

"""

# revision identifiers, used by Alembic.
revision = '16b50a2c53b'
down_revision = '4a7e5abdf57'

from alembic import op

import sqlalchemy as sa


def upgrade():
    connection = op.get_bind()

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('short_name', sa.String(length=80), nullable=True))
    op.create_unique_constraint("dept_short_name", 'departments', ['short_name'])
    ### end Alembic commands ###




def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("dept_short_name", 'departments', type_='unique')
    op.drop_column('departments', 'short_name')
    ### end Alembic commands ###
