"""empty message

Revision ID: 17b38c3d5e7
Revises: 331c513e8d4
Create Date: 2015-09-07 19:56:25.897494

"""

# revision identifiers, used by Alembic.
revision = '17b38c3d5e7'
down_revision = '331c513e8d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serviceTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=36), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serviceTypes')
    ### end Alembic commands ###
