"""empty message

Revision ID: 1c306b9d32
Revises: 58a10a2d8e4
Create Date: 2015-09-15 12:14:05.356636

"""

# revision identifiers, used by Alembic.
revision = '1c306b9d32'
down_revision = '58a10a2d8e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use_of_force_incidents', sa.Column('received_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('use_of_force_incidents', 'received_date')
    ### end Alembic commands ###
