"""empty message

Revision ID: 21dd34bbb19
Revises: 4ffa73ef2b8
Create Date: 2015-09-17 17:25:39.947908

"""

# revision identifiers, used by Alembic.
revision = '21dd34bbb19'
down_revision = '4ffa73ef2b8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use_of_force_incidents', sa.Column('beat', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('division', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('office_weapon_used', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('officer_force_type', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('officer_race', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('precinct', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('resident_hospitalized', sa.Boolean(), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('resident_injured', sa.Boolean(), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('resident_race', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('resident_resist_type', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('resident_weapon_used', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('shift', sa.String(length=255), nullable=True))
    op.alter_column('use_of_force_incidents', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('use_of_force_incidents', 'month')
    op.drop_column('use_of_force_incidents', 'hour')
    op.drop_column('use_of_force_incidents', 'year')
    op.drop_column('use_of_force_incidents', 'citizen_hospitalized')
    op.drop_column('use_of_force_incidents', 'citizen_weapon')
    op.drop_column('use_of_force_incidents', 'citizen_injured')
    op.drop_column('use_of_force_incidents', 'received_date')
    op.drop_column('use_of_force_incidents', 'day_of_week')
    op.drop_column('use_of_force_incidents', 'status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use_of_force_incidents', sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('day_of_week', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('received_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('citizen_injured', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('citizen_weapon', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('citizen_hospitalized', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('use_of_force_incidents', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('use_of_force_incidents', 'shift')
    op.drop_column('use_of_force_incidents', 'resident_weapon_used')
    op.drop_column('use_of_force_incidents', 'resident_resist_type')
    op.drop_column('use_of_force_incidents', 'resident_race')
    op.drop_column('use_of_force_incidents', 'resident_injured')
    op.drop_column('use_of_force_incidents', 'resident_hospitalized')
    op.drop_column('use_of_force_incidents', 'precinct')
    op.drop_column('use_of_force_incidents', 'officer_race')
    op.drop_column('use_of_force_incidents', 'officer_force_type')
    op.drop_column('use_of_force_incidents', 'office_weapon_used')
    op.drop_column('use_of_force_incidents', 'division')
    op.drop_column('use_of_force_incidents', 'beat')
    ### end Alembic commands ###
