"""empty message

Revision ID: 22a9ff0220c
Revises: 3434f410ad7
Create Date: 2015-09-04 16:31:49.356342

"""

# revision identifiers, used by Alembic.
revision = '22a9ff0220c'
down_revision = '3434f410ad7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    ### end Alembic commands ###
