"""empty message

Revision ID: 23353b28d77
Revises: b13e5a5233
Create Date: 2015-10-29 16:25:19.836266

"""

# revision identifiers, used by Alembic.
revision = '23353b28d77'
down_revision = 'b13e5a5233'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demographic_values', 'gender')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographic_values', sa.Column('gender', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    ### end Alembic commands ###
