"""empty message

Revision ID: 24987646046
Revises: 529d8396153
Create Date: 2015-09-18 11:52:24.133128

"""

# revision identifiers, used by Alembic.
revision = '24987646046'
down_revision = '529d8396153'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use_of_force_incidents', sa.Column('officer_years_of_service', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('use_of_force_incidents', 'officer_years_of_service')
    ### end Alembic commands ###
