"""empty message

Revision ID: 30e29c63aa6
Revises: 43fd1bb4848
Create Date: 2015-09-16 13:37:37.068522

"""

# revision identifiers, used by Alembic.
revision = '30e29c63aa6'
down_revision = '43fd1bb4848'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useOfForceIncidents', 'received_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useOfForceIncidents', sa.Column('received_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
