"""empty message

Revision ID: 32f2dcfc96d
Revises: 24987646046
Create Date: 2015-09-21 09:56:15.341931

"""

# revision identifiers, used by Alembic.
revision = '32f2dcfc96d'
down_revision = '24987646046'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denominator_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('arrests', sa.Integer(), nullable=True),
    sa.Column('calls_for_service', sa.Integer(), nullable=True),
    sa.Column('officer_initiated_calls', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('denominator_values')
    ### end Alembic commands ###
