"""empty message

Revision ID: 331a821cc4a
Revises: 585a75fc356
Create Date: 2015-10-12 14:24:50.301061

"""

# revision identifiers, used by Alembic.
revision = '331a821cc4a'
down_revision = '585a75fc356'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer_involved_shootings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('opaque_id', sa.String(length=255), nullable=False),
    sa.Column('occured_date', sa.DateTime(), nullable=True),
    sa.Column('division', sa.String(length=255), nullable=True),
    sa.Column('precinct', sa.String(length=255), nullable=True),
    sa.Column('shift', sa.String(length=255), nullable=True),
    sa.Column('beat', sa.String(length=255), nullable=True),
    sa.Column('disposition', sa.String(length=255), nullable=True),
    sa.Column('census_tract', sa.String(length=255), nullable=True),
    sa.Column('officer_force_type', sa.String(length=255), nullable=True),
    sa.Column('resident_weapon_used', sa.String(length=255), nullable=True),
    sa.Column('service_type', sa.String(length=255), nullable=True),
    sa.Column('resident_race', sa.String(length=255), nullable=True),
    sa.Column('officer_race', sa.String(length=255), nullable=True),
    sa.Column('resident_sex', sa.String(length=255), nullable=True),
    sa.Column('officer_sex', sa.String(length=255), nullable=True),
    sa.Column('officer_identifier', sa.String(length=255), nullable=True),
    sa.Column('officer_years_of_service', sa.Integer(), nullable=True),
    sa.Column('officer_age', sa.String(length=255), nullable=True),
    sa.Column('resident_age', sa.String(length=255), nullable=True),
    sa.Column('officer_condition', sa.String(length=255), nullable=True),
    sa.Column('resident_condition', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citizen_complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('opaque_id', sa.String(length=255), nullable=False),
    sa.Column('occured_date', sa.DateTime(), nullable=True),
    sa.Column('division', sa.String(length=255), nullable=True),
    sa.Column('precinct', sa.String(length=255), nullable=True),
    sa.Column('shift', sa.String(length=255), nullable=True),
    sa.Column('beat', sa.String(length=255), nullable=True),
    sa.Column('disposition', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('census_tract', sa.String(length=255), nullable=True),
    sa.Column('resident_race', sa.String(length=255), nullable=True),
    sa.Column('officer_race', sa.String(length=255), nullable=True),
    sa.Column('resident_sex', sa.String(length=255), nullable=True),
    sa.Column('officer_sex', sa.String(length=255), nullable=True),
    sa.Column('officer_identifier', sa.String(length=255), nullable=True),
    sa.Column('officer_years_of_service', sa.Integer(), nullable=True),
    sa.Column('officer_age', sa.String(length=255), nullable=True),
    sa.Column('resident_age', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('citizen_complaint')
    op.add_column('use_of_force_incidents', sa.Column('officer_condition', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('resident_condition', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('use_of_force_incidents', 'resident_condition')
    op.drop_column('use_of_force_incidents', 'officer_condition')
    op.create_table('citizen_complaint',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opaque_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('occured_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('division', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('precinct', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('shift', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('beat', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('disposition', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('census_tract', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resident_race', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('officer_race', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resident_sex', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('officer_sex', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('officer_identifier', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('officer_years_of_service', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('officer_age', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resident_age', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='citizen_complaint_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='citizen_complaint_pkey')
    )
    op.drop_table('citizen_complaints')
    op.drop_table('officer_involved_shootings')
    ### end Alembic commands ###
