"""empty message

Revision ID: 331c513e8d4
Revises: 22a9ff0220c
Create Date: 2015-09-07 14:37:53.570197

"""

# revision identifiers, used by Alembic.
revision = '331c513e8d4'
down_revision = '22a9ff0220c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('months',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('months')
    ### end Alembic commands ###
