"""empty message

Revision ID: 3434f410ad7
Revises: 28296e3a641
Create Date: 2015-09-02 15:41:27.014239

"""

# revision identifiers, used by Alembic.
revision = '3434f410ad7'
down_revision = '28296e3a641'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'type')
    op.drop_table('extractors')
    ### end Alembic commands ###
