"""empty message

Revision ID: 38f457822b3
Revises: 23353b28d77
Create Date: 2015-10-30 13:51:52.077037

"""

# revision identifiers, used by Alembic.
revision = '38f457822b3'
down_revision = '23353b28d77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('denominator_values', 'calls_for_service')
    op.drop_column('denominator_values', 'officer_initiated_calls')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('denominator_values', sa.Column('officer_initiated_calls', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('denominator_values', sa.Column('calls_for_service', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
