"""empty message

Revision ID: 4137d3521d5
Revises: 471223798fc
Create Date: 2015-10-12 07:31:48.954892

"""

# revision identifiers, used by Alembic.
revision = '4137d3521d5'
down_revision = '471223798fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('citizen_complaint_opaque_id_key', 'citizen_complaint', type_='unique')
    op.drop_constraint('use_of_force_incidents_opaque_id_key', 'use_of_force_incidents', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('use_of_force_incidents_opaque_id_key', 'use_of_force_incidents', ['opaque_id'])
    op.create_unique_constraint('citizen_complaint_opaque_id_key', 'citizen_complaint', ['opaque_id'])
    ### end Alembic commands ###
