"""empty message

Revision ID: 43fd1bb4848
Revises: 1c306b9d32
Create Date: 2015-09-16 11:42:55.297932

"""

# revision identifiers, used by Alembic.
revision = '43fd1bb4848'
down_revision = '1c306b9d32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use_of_force_incidents', sa.Column('census_tract', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('citizen_weapon', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('use_of_force_incidents', 'citizen_weapon')
    op.drop_column('use_of_force_incidents', 'census_tract')
    ### end Alembic commands ###
