"""empty message

Revision ID: 471223798fc
Revises: 1a869ac514c
Create Date: 2015-10-08 11:36:09.930401

"""

# revision identifiers, used by Alembic.
revision = '471223798fc'
down_revision = '1a869ac514c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use_of_force_incidents', sa.Column('officer_sex', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('resident_sex', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('use_of_force_incidents', 'resident_sex')
    op.drop_column('use_of_force_incidents', 'officer_sex')
    ### end Alembic commands ###
