"""empty message

Revision ID: 4a7e5abdf57
Revises: 507f3182b84
Create Date: 2015-11-09 20:16:19.255350

"""

# revision identifiers, used by Alembic.
revision = '4a7e5abdf57'
down_revision = '507f3182b84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officer_involved_shootings', sa.Column('officer_weapon_used', sa.String(length=255), nullable=True))
    op.drop_column('officer_involved_shootings', 'officer_force_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officer_involved_shootings', sa.Column('officer_force_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('officer_involved_shootings', 'officer_weapon_used')
    ### end Alembic commands ###
