"""empty message

Revision ID: 4e98ea7e43d
Revises: 52eaf89477f
Create Date: 2016-01-27 15:32:59.724051

"""

# revision identifiers, used by Alembic.
revision = '4e98ea7e43d'
down_revision = '52eaf89477f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'users', ['password_reset_uuid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password_reset_uuid')
    ### end Alembic commands ###
