"""empty message

Revision ID: 507f3182b84
Revises: 38f457822b3
Create Date: 2015-11-09 15:59:37.154821

"""

# revision identifiers, used by Alembic.
revision = '507f3182b84'
down_revision = '38f457822b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('denominator_values', sa.Column('officers_out_on_service', sa.Integer(), nullable=True))
    op.drop_column('denominator_values', 'arrests')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('denominator_values', sa.Column('arrests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('denominator_values', 'officers_out_on_service')
    ### end Alembic commands ###
