"""empty message

Revision ID: 51524883509
Revises: 16b50a2c53b
Create Date: 2015-12-21 15:33:48.694126

"""

# revision identifiers, used by Alembic.
revision = '51524883509'
down_revision = '16b50a2c53b'

from alembic import op
import sqlalchemy as sa
from comport.department.models import Department
from comport.database import db
from sqlalchemy.orm import  Session


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    for department in session.query(Department):
        short_name = "".join([x[0] for x in department.name.split(" ")])
        department.short_name = short_name
    session.commit()


    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'short_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'short_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    ### end Alembic commands ###
