"""empty message

Revision ID: 52887f8e06b
Revises: 33fcc9c4867
Create Date: 2015-09-23 11:44:35.366896

"""

# revision identifiers, used by Alembic.
revision = '52887f8e06b'
down_revision = '33fcc9c4867'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen_complaint', sa.Column('category', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen_complaint', 'category')
    ### end Alembic commands ###
