"""empty message

Revision ID: 529d8396153
Revises: 21dd34bbb19
Create Date: 2015-09-18 11:39:54.598704

"""

# revision identifiers, used by Alembic.
revision = '529d8396153'
down_revision = '21dd34bbb19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use_of_force_incidents', sa.Column('officer_identifier', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('officer_weapon_used', sa.String(length=255), nullable=True))
    op.drop_column('use_of_force_incidents', 'office_weapon_used')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use_of_force_incidents', sa.Column('office_weapon_used', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('use_of_force_incidents', 'officer_weapon_used')
    op.drop_column('use_of_force_incidents', 'officer_identifier')
    ### end Alembic commands ###
