"""empty message

Revision ID: 5660db12b2c9
Revises: None
Create Date: 2015-09-01 17:23:59.146727

"""

# revision identifiers, used by Alembic.
revision = '5660db12b2c9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'roles_name_key', 'roles', type_='unique')
    op.drop_column('users', 'is_admin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'roles_name_key', 'roles', ['name'])
    ### end Alembic commands ###
