"""empty message

Revision ID: 569aad8d933
Revises: 4f5fcadcf2d
Create Date: 2015-10-22 13:05:54.124697

"""

# revision identifiers, used by Alembic.
revision = '569aad8d933'
down_revision = '4f5fcadcf2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
