"""empty message

Revision ID: 585a75fc356
Revises: 4137d3521d5
Create Date: 2015-10-12 08:31:22.051331

"""

# revision identifiers, used by Alembic.
revision = '585a75fc356'
down_revision = '4137d3521d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen_complaint', sa.Column('officer_age', sa.String(length=255), nullable=True))
    op.add_column('citizen_complaint', sa.Column('resident_age', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('officer_age', sa.String(length=255), nullable=True))
    op.add_column('use_of_force_incidents', sa.Column('resident_age', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('use_of_force_incidents', 'resident_age')
    op.drop_column('use_of_force_incidents', 'officer_age')
    op.drop_column('citizen_complaint', 'resident_age')
    op.drop_column('citizen_complaint', 'officer_age')
    ### end Alembic commands ###
