"""empty message

Revision ID: 58a10a2d8e4
Revises: 875c52a485
Create Date: 2015-09-15 12:01:23.762266

"""

# revision identifiers, used by Alembic.
revision = '58a10a2d8e4'
down_revision = '875c52a485'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('use_of_force_incidents', sa.Column('occured_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('use_of_force_incidents', 'occured_date')
    ### end Alembic commands ###
