"""empty message

Revision ID: 6d30846080b2
Revises: 720df9948a25
Create Date: 2016-06-21 15:40:00.525317

"""

# revision identifiers, used by Alembic.
revision = '6d30846080b2'
down_revision = '720df9948a25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_public', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'is_public')
    ### end Alembic commands ###
