"""empty message

Revision ID: a6192071a8
Revises: 569aad8d933
Create Date: 2015-10-22 13:27:06.090940

"""

# revision identifiers, used by Alembic.
revision = 'a6192071a8'
down_revision = '569aad8d933'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'how_you_can_use_this_data')
    op.drop_column('departments', 'contact_us')
    op.drop_column('departments', 'why_we_are_doing_this')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('why_we_are_doing_this', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('departments', sa.Column('contact_us', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('departments', sa.Column('how_you_can_use_this_data', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
