"""empty message

Revision ID: b13e5a5233
Revises: 2357b6b3d76
Create Date: 2015-10-28 11:09:55.756737

"""

# revision identifiers, used by Alembic.
revision = 'b13e5a5233'
down_revision = '2357b6b3d76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractors', sa.Column('last_contact', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extractors', 'last_contact')
    ### end Alembic commands ###
