"""empty message

Revision ID: f0526891fa
Revises: 17b38c3d5e7
Create Date: 2015-09-07 20:25:13.536996

"""

# revision identifiers, used by Alembic.
revision = 'f0526891fa'
down_revision = '17b38c3d5e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractors', sa.Column('next_month', sa.Integer(), nullable=True))
    op.add_column('extractors', sa.Column('next_year', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extractors', 'next_year')
    op.drop_column('extractors', 'next_month')
    ### end Alembic commands ###
