"""empty message

Revision ID: fecca96b9d
Revises: a6192071a8
Create Date: 2015-10-22 15:45:21.928604

"""

# revision identifiers, used by Alembic.
revision = 'fecca96b9d'
down_revision = 'a6192071a8'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('use_of_force_incidents', 'officer_years_of_service')
    op.add_column('use_of_force_incidents', sa.Column('officer_years_of_service', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('use_of_force_incidents', 'officer_years_of_service')
    op.add_column('use_of_force_incidents', sa.Column('officer_years_of_service', sa.Integer(), nullable=True))
    ### end Alembic commands ###
