class DepartmentDefaults:
    what_this_is = """
    Here's what this is:
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut placerat ullamcorper justo, vel consectetur eros cursus sit amet. Nunc quam odio, venenatis sit amet justo vel, fringilla ultricies est. Mauris at luctus magna. Vestibulum et mauris nec quam dictum euismod. Integer mollis iaculis ultrices. Morbi ullamcorper mattis lorem in molestie. Phasellus id urna lacus. Proin felis ex, hendrerit et quam in, aliquet mollis nulla. Curabitur non faucibus sem. Sed faucibus fermentum tempus. Pellentesque sit amet erat venenatis justo varius imperdiet. Nulla cursus porttitor orci sodales fermentum. Ut eu orci eget odio commodo malesuada ac ut enim. Quisque vel vehicula ex. Vivamus non tempus lacus, ut consectetur tortor.
    Mauris convallis massa nec viverra iaculis. Vivamus a quam non velit pretium cursus. Praesent sit amet nibh leo. Nam vel lorem semper, lobortis nisi ac, pharetra sapien. Sed tempus urna eget sapien auctor dignissim et vel arcu. Ut fringilla porttitor cursus. Ut vulputate, metus vel volutpat laoreet, neque mi vehicula risus, quis pharetra nunc mi vel ex. Nunc dictum ac sem at dapibus. Sed tristique feugiat hendrerit. Aliquam nec ante lorem. Nulla facilisi. Aenean iaculis pretium quam sit amet lacinia. Etiam porttitor ipsum vel lorem rhoncus pellentesque. Donec eu purus augue. Praesent eleifend rhoncus convallis. Morbi tristique elit non quam molestie tristique.
    """
    why_we_are_doing_this = """
    Here's why we're doing this:
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras dignissim justo id urna accumsan bibendum. Aenean ac ultricies ex. Cras vel eleifend eros. Quisque metus orci, posuere eu elementum vel, pharetra a nulla. Quisque tortor eros, tincidunt id ante nec, sollicitudin dictum justo. Morbi pretium odio quis nisi pretium, sed bibendum felis cursus. Vestibulum sed vestibulum urna, sed pharetra dolor. Nulla vulputate risus id purus dapibus gravida. Morbi porttitor ante eget mattis tempus. Mauris nec velit odio. Nullam semper diam vel est mattis porttitor. Fusce magna risus, posuere ac consequat at, elementum quis odio. Morbi sodales auctor nibh, id tincidunt ex tristique vitae. Maecenas bibendum metus nec accumsan consequat. Sed eu ullamcorper turpis.
    Nullam eu elit a mauris lacinia semper. Mauris facilisis arcu ut arcu tincidunt, in ullamcorper lacus semper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin convallis maximus augue sit amet viverra. Vivamus laoreet felis in faucibus congue. Donec nec erat ipsum. Nam mollis quam in maximus ultrices. Vivamus dictum a lacus ut imperdiet. Mauris rhoncus dui et leo scelerisque consequat. Sed ac eros faucibus, lacinia elit at, iaculis tortor. Proin cursus fringilla cursus. Vivamus malesuada congue mauris, auctor malesuada nulla euismod at. Mauris justo ligula, finibus eu sollicitudin sed, vehicula a risus. Vestibulum euismod quis ante sit amet suscipit.
    """
    how_you_can_use_this_data = """
    Here's how you can use this data:
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque mauris augue, pharetra vitae elementum in, pharetra vitae eros. Nullam ut rutrum leo. Phasellus fringilla, erat id blandit tincidunt, elit lorem venenatis ligula, vitae ultrices lectus erat sed ante. Pellentesque sed imperdiet magna. Nullam ultrices euismod magna, at condimentum eros porttitor nec. Donec accumsan faucibus felis non convallis. In feugiat nec sapien at aliquam. Phasellus pharetra ultrices ipsum quis aliquam. In ultrices, libero et pulvinar feugiat, diam purus rutrum leo, sit amet ornare eros massa nec sem. Proin id ipsum in leo consectetur blandit in vel metus.
    Vestibulum felis nibh, mollis eu sagittis id, cursus at massa. Sed scelerisque vulputate dui, sed eleifend massa sodales non. Fusce faucibus nulla libero, a auctor nulla dignissim vitae. Donec tincidunt, leo et maximus commodo, erat purus viverra nisl, eu aliquam eros felis a ante. Phasellus volutpat odio vitae mollis consectetur. Ut vulputate iaculis sapien, dapibus semper sem tincidunt in. Proin vulputate placerat odio, a efficitur enim finibus a. Proin gravida turpis erat, in gravida quam volutpat id. Vestibulum dapibus ipsum faucibus, imperdiet turpis eu, varius est. Donec at erat eu nibh tincidunt congue vel eu ante.
    """
    contact_us = """
    Here's how you can contact us:
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sed risus nec dui finibus suscipit nec nec felis. Cras ultricies et nisl vel sollicitudin. Morbi nisl diam, efficitur eget viverra sed, elementum ac libero. Proin at placerat nisi. Etiam sit amet neque ipsum. Aenean luctus magna sed sapien dictum malesuada. Nulla eget magna at quam pretium efficitur eu vitae lectus. Nam volutpat mauris a porta vehicula. Vivamus non velit at libero mattis faucibus. Sed ut urna a urna vehicula lobortis sit amet non quam.
    """
